### ISSUE TITLE
Zmena API

### ISSUE THREAD

**Issue by miroc** [BRACKETS-by-TRIAD/remp-scenario-builder#2]
Miesto typu elementu `Action` (do ktorej sme vkladali typ akcie) pouzivame priamo typ `Email`, aby sme zjednotili format akym sa popisuju elementy. Zmenil som aj popis API v Dropbox specifikacii.

Mozete to prosim reflektovat aj v scenario-builderi? Diky!

**Comment by matejminar** [comment]
Jasne, kludne.

Uz ste menili aj API?
Lebo takyto payload mi vracia 409:

`{"name":"Unnamed scenario","triggers":{"b6f1a244-6031-4abe-9234-644a3d67194e":{"id":"b6f1a244-6031-4abe-9234-644a3d67194e","name":"","type":"event","event":{"code":"user_created"},"elements":["4ab453f3-986f-4990-b39d-4c2fbc584fa9"]}},"elements":{"4ab453f3-986f-4990-b39d-4c2fbc584fa9":{"id":"4ab453f3-986f-4990-b39d-4c2fbc584fa9","name":"","type":"email","email":{"code":"welcome_email_with_password","descendants":[]}}},"visual":{"b6f1a244-6031-4abe-9234-644a3d67194e":{"x":174,"y":256},"4ab453f3-986f-4990-b39d-4c2fbc584fa9":{"x":403,"y":241}}}`

**Comment by miroc** [comment]
Diky, trocha ste nas predbehli :) 
API este nie je zmenene, mame na to ready merge request, mergneme na zaciatku tyzdna buduceho pravdepodobne (@rootpd).

**Comment by miroc** [comment]
Uz by to malo byt nasadene.

**Comment by matejminar** [comment]
Parada, funguje. 
Dakujem
